name: build

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Verification Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Install Dependencies
        run: pnpm install

      - name: Run Check
        run: pnpm type:check

      - name: Run Code Formatting Check
        run: pnpm fmt

      - name: Run Build
        run: pnpm build

      - name: Run Tests
        run: pnpm test
