name: release

on:
  push:
    branches:
      - main

# Required permissions for semantic-release to create tags, releases, and status checks
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Fetches all git history so semantic-release can read tags

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install Dependencies
        run: pnpm install

      - name: Run Check
        run: pnpm type:check

      - name: Run Formatter
        run: pnpm fmt

      - name: Run Build
        run: pnpm build

      - name: Run Tests
        run: pnpm test

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm exec semantic-release
